### ISSUE TITLE
Activities Editable from Activity view Screen if "View" permission is given

### ISSUE THREAD

**Issue by shaun-a-lot** [JMAConsulting/biz.jmaconsulting.activitytypeacl#22]
If staff do not have permission to Edit an activity they can still edit if they have the ability to View
For instance, if staff with View and Add permission only access a Case screen, then click View an activity, then the activity View screen gives them the option to Edit (which they can proceed to Edit and save the activity).

Image 1 - What a staff member with Add and View only sees in eth activity summary of a case
![Add and View Permission only](https://user-images.githubusercontent.com/95344258/144206325-b9063fb9-f5ff-4ee4-b4f7-ab9547522c5c.png)

Image 2 - Showing the Edit option is given within in the activity view, despite that permission not being assigned to that staff member role
![Edit option shown in activity view](https://user-images.githubusercontent.com/95344258/144206334-2733424c-33fe-4a2a-8495-c4a772a0819c.png)

**Comment by lukeyangjma** [comment]
![Screen Shot 2022-06-14 at 7 37 27 AM](https://user-images.githubusercontent.com/105511138/173568447-a256a88f-8558-4472-b5c1-199cac190b89.png)

**Comment by Edzelopez** [comment]
We've addressed this in a new PR here: https://github.com/JMAConsulting/biz.jmaconsulting.activitytypeacl/pull/26

You can either apply the PR to your instance, or wait for a new release scheduled this week. Thanks!

**Comment by shaun-a-lot** [comment]
I have applied the patch but I am still having the same issue whereby those with view access (image 1) to an activity can then see Edit as a selectable option in the view popup and can then edit the details and save (image 2).

<img width="435" alt="image (1)" src="https://user-images.githubusercontent.com/95344258/176174357-4a41898c-2eab-4569-9236-775df4208e59.png">
<img width="422" alt="image (2)" src="https://user-images.githubusercontent.com/95344258/176174366-5395c103-3800-4bcc-8640-deba700a565f.png">

**Comment by Edzelopez** [comment]
@lukeyangjma can you please extend your patch to work on the case activity view screen as well?

**Comment by lukeyangjma** [comment]
@shaun-a-lot The issue should be fixed now with the latest commit on #26. Let me know if it's working or not.

**Comment by shaun-a-lot** [comment]
I have applied this, but still having the same issue. I have double checked the permissions, cleared caches but still the same I'm afraid.

**Comment by lukeyangjma** [comment]
@shaun-a-lot Some changes were implemented just now. Try and see if the most recent commit on #26 fixes the issue. If not, could you provide step-by-step instructions of how to navigate to the page the issue is occurring?

**Comment by shaun-a-lot** [comment]
Hi @lukeyangjma I applied it this morning and it is working. Thanks so much for getting that sorted, I really appreciate it.

**Comment by JoeMurray** [comment]
You're welcome @shaun-a-lot . We also appreciate your willingness and patience to help us with testing.
